defaults: &defaults
  working_directory: ~/repo

version: 2
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm run lint
      - run: npm run e2e
      - run: npm run build
      # Persist entire project directory to the next job
      - persist_to_workspace:
          root: dist
          paths:
            - "**"
      - run: exit 0
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: ':bb-dance::pet-bb-head::bb-begging: Circle BB job success!'
          failure_message: ':bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood: Circle BB job failed!'

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Deploy entire directory
          command: aws s3 cp . s3://bb-reader-bucket --recursive
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: ':bb-dance::pet-bb-head::bb-begging: Circle BB job success!'
          failure_message: ':bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood: Circle BB job failed!'
